name: API To Excel

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Packages
      run: |
        pip install pandas
        pip install requests
        pip install openpyxl

    - name: Run Script
      run: python API.py

    - name: Upload Excel
      uses: actions/upload-artifact@v4
      with:
        name: excel-report
        path: users.xlsx
